/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    exercises: Exercise;
    programs: Program;
    'program-assignments': ProgramAssignment;
    'trainer-clients': TrainerClient;
    'workout-sessions': WorkoutSession;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'program-assignments': ProgramAssignmentsSelect<false> | ProgramAssignmentsSelect<true>;
    'trainer-clients': TrainerClientsSelect<false> | TrainerClientsSelect<true>;
    'workout-sessions': WorkoutSessionsSelect<false> | WorkoutSessionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  roles: ('athlete' | 'trainer' | 'admin')[];
  /**
   * URL or local asset path
   */
  photo?: string | null;
  birthDate?: string | null;
  /**
   * Years
   */
  age?: number | null;
  /**
   * Body weight in kilograms
   */
  weightKg?: number | null;
  sex?: ('female' | 'male' | 'other' | 'unspecified') | null;
  /**
   * Training level used when generating or adapting a program
   */
  level?: ('beginner' | 'returning' | 'intermediate' | 'advanced') | null;
  /**
   * Injuries, limitations, pregnancy, or anything a program should respect
   */
  conditionNotes?: string | null;
  /**
   * Where you usually train
   */
  trainingVenue?: ('home' | 'gym' | 'both') | null;
  /**
   * Display units for load
   */
  preferredUnits?: ('kg' | 'lbs') | null;
  /**
   * Default rest between sets, in seconds
   */
  defaultRestSeconds?: number | null;
  gender?: string | null;
  fitnessLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  goals?: ('generalFitness' | 'strength' | 'mobility' | 'cardio' | 'weightManagement' | 'bodyToning')[] | null;
  /**
   * Structured athlete profile from the StayAble app (health, goals, lifestyle).
   */
  assessment?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  language: 'en' | 'he';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Matches an exercise clientId when this is a catalog photo.
   */
  clientId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Exercise library. Seeded rows keep ids like ex-squat. New rows get a client id automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  id: string;
  /**
   * Stable id for the app. Set automatically.
   */
  clientId: string;
  adminTitle?: string | null;
  deleted?: boolean | null;
  name: {
    en: string;
    he?: string | null;
  };
  description: {
    en: string;
    he?: string | null;
  };
  /**
   * Formatted steps shown in the app.
   */
  instructions: {
    en: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    he?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  safetyNotes: {
    en: string;
    he?: string | null;
  };
  image?: (string | null) | Media;
  /**
   * Flutter asset path, e.g. assets/exercises/ex-squat.png
   */
  photoPath?: string | null;
  category: 'warmUp' | 'mobility' | 'strength' | 'cardio' | 'stretching' | 'coolDown';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /**
   * Where this exercise can be performed
   */
  venue: 'home' | 'gym' | 'both';
  /**
   * Main training style: resistance, cardio endurance, intervals, or everyday movement.
   */
  workoutType: 'strength' | 'aerobic' | 'hiit' | 'functional';
  /**
   * Optional machine number in the gymnastics room
   */
  gymNumber?: number | null;
  duration?: number | null;
  repetitions?: number | null;
  targetMuscles?: string[] | null;
  equipment?:
    | (
        | 'none'
        | 'mat'
        | 'resistanceBand'
        | 'dumbbells'
        | 'chair'
        | 'machine'
        | 'barbell'
        | 'cable'
        | 'kettlebell'
        | 'bench'
      )
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable collection of exercises. You can edit or delete a program after athletes have trained it. Past sessions keep what they logged. Delete removes assignments; session history stays.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: string;
  /**
   * Stable id for the app. Set automatically.
   */
  clientId: string;
  deleted?: boolean | null;
  /**
   * Who created this template, usually a trainer. Not the athlete who follows it.
   */
  owner: string | User;
  name: string;
  description?: string | null;
  active?: boolean | null;
  /**
   * Home, gymnastics room, or both in one program
   */
  venue: 'home' | 'gym' | 'mixed';
  /**
   * The workout as a single list. When an athlete trains is set on the assignment.
   */
  exercises?:
    | {
        /**
         * Stable id for the app. Set automatically.
         */
        clientId: string;
        exercise: string | Exercise;
        sortOrder: number;
        sets: number;
        repetitions?: number | null;
        /**
         * Seconds
         */
        duration?: number | null;
        /**
         * Planned load in kilograms
         */
        loadKg?: number | null;
        /**
         * Seconds
         */
        rest?: number | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gives an athlete a program. Set when they train here (weekly, daily, or custom). Leave refinements empty to use the program defaults, or override sets, reps, duration, and load for this person only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-assignments".
 */
export interface ProgramAssignment {
  id: string;
  /**
   * Stable id for the app. Set automatically.
   */
  clientId: string;
  adminTitle?: string | null;
  deleted?: boolean | null;
  /**
   * The exercise collection this athlete will follow.
   */
  program: string | Program;
  athlete: string | User;
  assignedBy: string | User;
  /**
   * When this athlete trains. Specific to this person, not the program.
   */
  scheduleType: 'daily' | 'weekly' | 'custom';
  startDate?: string | null;
  endDate?: string | null;
  active?: boolean | null;
  /**
   * Which days this athlete trains. Weekly uses weekday (1 = Monday). Custom uses a date. Daily can list every weekday or be left empty.
   */
  scheduleDays?:
    | {
        /**
         * Stable id for the app. Set automatically.
         */
        clientId: string;
        /**
         * 1 = Monday … 7 = Sunday
         */
        weekday?: number | null;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional per-exercise overrides for this athlete. Match programExerciseClientId to the slug of a slot on the program. Leave a field empty to keep the program default.
   */
  refinements?:
    | {
        /**
         * Slug of the exercise slot on the program
         */
        programExerciseClientId: string;
        sets?: number | null;
        repetitions?: number | null;
        /**
         * Seconds
         */
        duration?: number | null;
        /**
         * Kilograms
         */
        loadKg?: number | null;
        /**
         * Seconds
         */
        rest?: number | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-clients".
 */
export interface TrainerClient {
  id: string;
  /**
   * Stable id for the app. Set automatically.
   */
  clientId: string;
  adminTitle?: string | null;
  deleted?: boolean | null;
  trainer: string | User;
  athlete: string | User;
  status: 'invited' | 'active' | 'declined' | 'ended';
  invitedAt?: string | null;
  acceptedAt?: string | null;
  endedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-sessions".
 */
export interface WorkoutSession {
  id: string;
  /**
   * Stable id for the app. Set automatically.
   */
  clientId: string;
  adminTitle?: string | null;
  deleted?: boolean | null;
  athlete: string | User;
  program?: (string | null) | Program;
  programDayClientId?: string | null;
  startedAt: string;
  completedAt?: string | null;
  duration?: number | null;
  status: 'planned' | 'started' | 'completed' | 'partiallyCompleted' | 'skipped' | 'cancelled';
  notes?: string | null;
  /**
   * Sets × reps × kilograms
   */
  totalVolumeKg?: number | null;
  activeDeviceId?: string | null;
  exercises?:
    | {
        /**
         * Stable id for the app. Set automatically.
         */
        clientId: string;
        exercise: string | Exercise;
        programExerciseClientId?: string | null;
        sortOrder: number;
        plannedSets: number;
        actualSets?: number | null;
        plannedRepetitions?: number | null;
        actualRepetitions?: number | null;
        plannedDuration?: number | null;
        actualDuration?: number | null;
        completed?: boolean | null;
        effort?: ('easy' | 'good' | 'difficult') | null;
        notes?: string | null;
        /**
         * Personal record on this exercise
         */
        personalRecord?: boolean | null;
        sets?:
          | {
              /**
               * Stable id for the app. Set automatically.
               */
              clientId: string;
              setNumber: number;
              plannedReps?: number | null;
              actualReps?: number | null;
              plannedDuration?: number | null;
              actualDuration?: number | null;
              plannedLoadKg?: number | null;
              actualLoadKg?: number | null;
              completed?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'exercises';
        value: string | Exercise;
      } | null)
    | ({
        relationTo: 'programs';
        value: string | Program;
      } | null)
    | ({
        relationTo: 'program-assignments';
        value: string | ProgramAssignment;
      } | null)
    | ({
        relationTo: 'trainer-clients';
        value: string | TrainerClient;
      } | null)
    | ({
        relationTo: 'workout-sessions';
        value: string | WorkoutSession;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  photo?: T;
  birthDate?: T;
  age?: T;
  weightKg?: T;
  sex?: T;
  level?: T;
  conditionNotes?: T;
  trainingVenue?: T;
  preferredUnits?: T;
  defaultRestSeconds?: T;
  gender?: T;
  fitnessLevel?: T;
  goals?: T;
  assessment?: T;
  language?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  clientId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  clientId?: T;
  adminTitle?: T;
  deleted?: T;
  name?:
    | T
    | {
        en?: T;
        he?: T;
      };
  description?:
    | T
    | {
        en?: T;
        he?: T;
      };
  instructions?:
    | T
    | {
        en?: T;
        he?: T;
      };
  safetyNotes?:
    | T
    | {
        en?: T;
        he?: T;
      };
  image?: T;
  photoPath?: T;
  category?: T;
  difficulty?: T;
  venue?: T;
  workoutType?: T;
  gymNumber?: T;
  duration?: T;
  repetitions?: T;
  targetMuscles?: T;
  equipment?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  clientId?: T;
  deleted?: T;
  owner?: T;
  name?: T;
  description?: T;
  active?: T;
  venue?: T;
  exercises?:
    | T
    | {
        clientId?: T;
        exercise?: T;
        sortOrder?: T;
        sets?: T;
        repetitions?: T;
        duration?: T;
        loadKg?: T;
        rest?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-assignments_select".
 */
export interface ProgramAssignmentsSelect<T extends boolean = true> {
  clientId?: T;
  adminTitle?: T;
  deleted?: T;
  program?: T;
  athlete?: T;
  assignedBy?: T;
  scheduleType?: T;
  startDate?: T;
  endDate?: T;
  active?: T;
  scheduleDays?:
    | T
    | {
        clientId?: T;
        weekday?: T;
        date?: T;
        id?: T;
      };
  refinements?:
    | T
    | {
        programExerciseClientId?: T;
        sets?: T;
        repetitions?: T;
        duration?: T;
        loadKg?: T;
        rest?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-clients_select".
 */
export interface TrainerClientsSelect<T extends boolean = true> {
  clientId?: T;
  adminTitle?: T;
  deleted?: T;
  trainer?: T;
  athlete?: T;
  status?: T;
  invitedAt?: T;
  acceptedAt?: T;
  endedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-sessions_select".
 */
export interface WorkoutSessionsSelect<T extends boolean = true> {
  clientId?: T;
  adminTitle?: T;
  deleted?: T;
  athlete?: T;
  program?: T;
  programDayClientId?: T;
  startedAt?: T;
  completedAt?: T;
  duration?: T;
  status?: T;
  notes?: T;
  totalVolumeKg?: T;
  activeDeviceId?: T;
  exercises?:
    | T
    | {
        clientId?: T;
        exercise?: T;
        programExerciseClientId?: T;
        sortOrder?: T;
        plannedSets?: T;
        actualSets?: T;
        plannedRepetitions?: T;
        actualRepetitions?: T;
        plannedDuration?: T;
        actualDuration?: T;
        completed?: T;
        effort?: T;
        notes?: T;
        personalRecord?: T;
        sets?:
          | T
          | {
              clientId?: T;
              setNumber?: T;
              plannedReps?: T;
              actualReps?: T;
              plannedDuration?: T;
              actualDuration?: T;
              plannedLoadKg?: T;
              actualLoadKg?: T;
              completed?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}