import type { SeedExercise } from './exercises'

const safety = {
  en: 'Low-impact and joint-friendly. Keep a sturdy chair nearby. Stop if you feel dizzy, short of breath, or sharp pain.',
  he: 'אימון בעצימה נמוכה וידידותי למפרקים. השאירו כיסא יציב בקרבת מקום. עצרו אם מופיעה סחרחורת, קוצר נשימה או כאב חד.',
}

export const aerobicProgramClientId = 'program-20min-aerobic'

/** From docs/20-Minute Aerobic Workout Routine.pdf */
export const aerobicProgramPlan = [
  { exerciseId: 'ex-high-march-chair', sortOrder: 1, sets: 2, duration: 60, rest: 0 },
  { exerciseId: 'ex-step-jacks-low', sortOrder: 2, sets: 2, duration: 60, rest: 0 },
  { exerciseId: 'ex-shadow-boxing', sortOrder: 3, sets: 2, duration: 45, rest: 15 },
  { exerciseId: 'ex-skater-taps', sortOrder: 4, sets: 2, duration: 45, rest: 15 },
  { exerciseId: 'ex-butt-kicks-lat', sortOrder: 5, sets: 2, duration: 45, rest: 15 },
  { exerciseId: 'ex-lateral-step-touch', sortOrder: 6, sets: 2, duration: 45, rest: 15 },
  { exerciseId: 'ex-seated-fast-feet', sortOrder: 7, sets: 3, duration: 30, rest: 30 },
  { exerciseId: 'ex-chair-incline-burpee', sortOrder: 8, sets: 3, duration: 30, rest: 30 },
  { exerciseId: 'ex-seated-quad-stretch', sortOrder: 9, sets: 1, duration: 120, rest: 0 },
] as const

export const aerobicScheduleDays = [
  { clientId: 'day-tue', weekday: 2 },
  { clientId: 'day-thu', weekday: 4 },
  { clientId: 'day-sat', weekday: 6 },
] as const

export const aerobicExercises: SeedExercise[] = [
  {
    clientId: 'ex-high-march-chair',
    name: { en: 'High March with Chair Support', he: 'צעידה גבוהה עם תמיכת כיסא' },
    description: {
      en: 'March in place next to a chair, lifting the knees and pumping the opposite arm.',
      he: 'צעידה במקום ליד כיסא, הרמת ברכיים והנעת היד הנגדית.',
    },
    instructions: {
      en: '1. Stand tall next to a sturdy chair, holding the backrest with one hand.\n2. March in place, lifting the knees to a comfortable height.\n3. Pump the opposite arm.\n4. Keep the chest up and land softly.',
      he: '1. עמדו זקוף ליד כיסא יציב, יד אחת על המשענת.\n2. צעדו במקום והרימו ברכיים לגובה נוח.\n3. הנעו את היד הנגדית.\n4. שמרו על גב זקוף ונחיתה רכה. ניתן להיעזר בגב הכיסא ליציבות.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-high-march-chair.png',
    category: 'warmUp',
    difficulty: 'beginner',
    venue: 'home',
    duration: 60,
    targetMuscles: ['cardiovascular', 'hipFlexors', 'core'],
    equipment: 'chair',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-step-jacks-low',
    name: { en: 'Step Jacks — Low Impact', he: 'סטפ ג׳קס בעצימה נמוכה' },
    description: {
      en: 'Side steps with arm reaches below shoulder height. No jumping.',
      he: 'פסיעות לצדדים עם הנעת ידיים מתחת לגובה הכתף. בלי קפיצה.',
    },
    instructions: {
      en: '1. Step wide to the right and reach the arms out to the sides.\n2. Return to center.\n3. Repeat to the left.\n4. Keep the arms at chest height if the shoulders are sensitive.',
      he: '1. פסיעה רחבה ימינה והוציאו ידיים לצדדים.\n2. חזרו למרכז.\n3. חזרו על הצד שמאל.\n4. פסיעה רחבה הצידה ללא קפיצה. שמרו ידיים בגובה החזה אם יש רגישות בכתפיים.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-step-jacks-low.png',
    category: 'warmUp',
    difficulty: 'beginner',
    venue: 'home',
    duration: 60,
    targetMuscles: ['cardiovascular', 'shoulders', 'hipFlexors'],
    equipment: 'none',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-shadow-boxing',
    name: { en: 'Seated or Standing Shadow Boxing', he: 'אגרוף צללים בעמידה או בישיבה' },
    description: {
      en: 'Controlled straight jabs, seated or standing, with the feet grounded.',
      he: 'אגרופים ישרים מבוקרים בעמידה או בישיבה, כפות רגליים יציבות.',
    },
    instructions: {
      en: '1. Sit or stand tall with feet wide and grounded.\n2. Throw light straight jabs, alternating hands.\n3. Keep the punches at a controlled pace and engage the core.\n4. Use a stable chair if you prefer to sit.',
      he: '1. שבו או עמדו זקוף, רגליים ברוחב נוח ויציבות.\n2. אגרופים ישרים קלים לסירוגין.\n3. שמרו על קצב מבוקר וליבה פעילה.\n4. אגרופים לפנים בקצב מבוקר. ניתן לבצע בישיבה על כיסא יציב.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-shadow-boxing.png',
    category: 'cardio',
    difficulty: 'beginner',
    venue: 'home',
    duration: 45,
    targetMuscles: ['cardiovascular', 'shoulders', 'core'],
    equipment: 'chair',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-skater-taps',
    name: { en: 'Low-Impact Skater Taps', he: 'צעדי מחליק עדינים' },
    description: {
      en: 'Light diagonal toe taps behind you, without dropping into a squat.',
      he: 'נגיעת אצבעות אלכסונית מאחור, בלי לרדת לסקווט.',
    },
    instructions: {
      en: '1. Stand tall.\n2. Step right and tap the left toes diagonally behind you.\n3. Alternate sides in a steady rhythm.\n4. Swing the arms naturally. Do not bend the knees deeply.',
      he: '1. עמדו זקוף.\n2. פסעו ימינה ונגעו באצבעות שמאל באלכסון מאחור.\n3. החליפו צד בקצב רגוע.\n4. נגיעת אצבעות קלה מאחור, ללא כפוף עמוק של הברכיים.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-skater-taps.png',
    category: 'cardio',
    difficulty: 'beginner',
    venue: 'home',
    duration: 45,
    targetMuscles: ['cardiovascular', 'glutes', 'hipFlexors'],
    equipment: 'none',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-butt-kicks-lat',
    name: { en: 'Gentle Butt Kicks with Lat Pulls', he: 'הרמת עקבים לישבן עם משיכת גב' },
    description: {
      en: 'Side-to-side steps with a gentle heel lift and elbows pulling back.',
      he: 'צעדים לצדדים עם הרמת עקב עדינה ומשיכת מרפקים לאחור.',
    },
    instructions: {
      en: '1. Step side to side.\n2. Bring the heel up toward the glute as you step.\n3. Pull the elbows back to the waist as the heel lifts.\n4. Keep the movement small and smooth.',
      he: '1. צעדו מצד לצד.\n2. הרימו עקב עדין לכיוון הישבן.\n3. משכו מרפקים לאחור לגובה המותניים.\n4. הרמת עקב אחורית עדינה ומשיכת מרפקים לאחור לחיזוק הגב העליון.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-butt-kicks-lat.png',
    category: 'cardio',
    difficulty: 'beginner',
    venue: 'home',
    duration: 45,
    targetMuscles: ['cardiovascular', 'glutes', 'back'],
    equipment: 'none',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-lateral-step-touch',
    name: { en: 'Lateral Step-Touch', he: 'צעד-צד לצדדים' },
    description: {
      en: 'Two side-steps right, a light tap, then two steps back left.',
      he: 'שתי פסיעות ימינה, נגיעה קלה, ושתי פסיעות חזרה שמאלה.',
    },
    instructions: {
      en: '1. Take two steps to the right.\n2. Tap the left foot on the floor.\n3. Take two steps back to the left.\n4. Keep the knees soft and the chest tall.',
      he: '1. שתי פסיעות ימינה.\n2. נגיעה קלה ברצפה.\n3. שתי פסיעות בחזרה שמאלה.\n4. שמרו על ברכיים רכות וחזה פתוח.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-lateral-step-touch.png',
    category: 'cardio',
    difficulty: 'beginner',
    venue: 'home',
    duration: 45,
    targetMuscles: ['cardiovascular', 'hipFlexors', 'glutes'],
    equipment: 'none',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-seated-fast-feet',
    name: { en: 'Seated Fast Feet', he: 'תיפוף רגליים מהיר בישיבה' },
    description: {
      en: 'Quick, light foot taps from the front edge of a chair.',
      he: 'תיפוף מהיר וקליל של כפות הרגליים מקצה הכיסא.',
    },
    instructions: {
      en: '1. Sit upright on the front edge of a chair.\n2. Lean back slightly with the core tight.\n3. Tap the feet as quickly as is comfortable.\n4. Keep the taps light.',
      he: '1. שבו זקוף על קצה הכיסא.\n2. נטו מעט לאחור עם ליבה מכווצת.\n3. תפפו ברגליים במהירות נוחה.\n4. ישיבה על קצה הכיסא ותיפוף מהיר וקליל של כפות הרגליים.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-seated-fast-feet.png',
    category: 'cardio',
    difficulty: 'beginner',
    venue: 'home',
    duration: 30,
    targetMuscles: ['cardiovascular', 'hipFlexors', 'core'],
    equipment: 'chair',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-chair-incline-burpee',
    name: { en: 'Chair Incline Burpee', he: 'בורפי בשיפוע על כיסא' },
    description: {
      en: 'Hands on a chair seat, step back to an incline plank, step in, and stand tall.',
      he: 'ידיים על מושב כיסא, צעידה לאחור לפלאנק בשיפוע, חזרה ועמידה.',
    },
    instructions: {
      en: '1. Place both hands on a fixed chair seat.\n2. Step back one foot at a time into a strong incline plank.\n3. Step the feet forward.\n4. Stand tall and reach overhead.',
      he: '1. הניחו ידיים על מושב כיסא יציב.\n2. צעדו לאחור רגל-רגל לפלאנק בשיפוע.\n3. צעדו לפנים.\n4. עמדו זקוף והרימו ידיים. הנחת ידיים על מושב הכיסא, צעידה לאחור לפלאנק, צעידה לפנים ועמידה ישרה.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-chair-incline-burpee.png',
    category: 'cardio',
    difficulty: 'beginner',
    venue: 'home',
    duration: 30,
    targetMuscles: ['cardiovascular', 'chest', 'core'],
    equipment: 'chair',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-seated-quad-stretch',
    name: { en: 'Seated Quad and Hip Flexor Stretch', he: 'מתיחת ארבע-ראשי ומכופפי ירך בישיבה' },
    description: {
      en: 'Sit sideways on a chair and drop the outside knee toward the floor.',
      he: 'ישיבה על צידי הכיסא והורדת הברך החיצונית כלפי הרצפה.',
    },
    instructions: {
      en: '1. Sit sideways on a sturdy chair.\n2. Drop the outside knee toward the floor.\n3. Keep the torso upright.\n4. Hold, then switch sides.',
      he: '1. שבו על צידי כיסא יציב.\n2. הורידו את הברך החיצונית כלפי הרצפה.\n3. החזיקו את הגו זקוף.\n4. החזיקו והחליפו צד.',
    },
    safetyNotes: safety,
    photo: 'assets/exercises/ex-seated-quad-stretch.png',
    category: 'coolDown',
    difficulty: 'beginner',
    venue: 'home',
    duration: 120,
    targetMuscles: ['quadriceps', 'hipFlexors'],
    equipment: 'chair',
    active: true,
    deleted: false,
  },
]
