import type { SeedExercise } from './exercises'

const safetyDefault = {
  en: 'Move within a comfortable range. Stop if you feel sharp pain.',
  he: 'הישארו בטווח נוח. עצרו אם מופיע כאב חד.',
}

/** Full-body gym plan from workout_plan.html. Skips squat, calf raise, dead bug, and bird dog — those already exist. */
export const fullBodyPlanExercises: SeedExercise[] = [
  {
    clientId: 'ex-leg-extension',
    name: { en: 'Leg Extension', he: 'פשיטת ברך במכונה' },
    description: {
      en: 'Machine knee extension for the quadriceps. Plan load: 28 kg, seat 3/3.',
      he: 'פשיטת ברך במכונה לארבע-ראשי. משקל בתוכנית: 28 ק״ג, כיוונון 3/3.',
    },
    instructions: {
      en: '1. Sit in the machine, back against the pad, chest tall.\n2. Align the knees with the machine pivot.\n3. Straighten the knees through a comfortable range.\n4. Lower slowly.\nBreathe: exhale on the extension, inhale on the way down.',
      he: '1. שב במכונה, יישר את הגב והצמד חזה לגב המושב.\n2. יישר ברכיים עד יישור מלא בטווח נוח.\n3. חזור לאט למצב ההתחלתי.\nנשימה: נושף ביישור, שואף בירידה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-leg-extension.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    repetitions: 10,
    targetMuscles: ['quadriceps'],
    equipment: 'machine',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-leg-press',
    name: { en: 'Leg Press', he: 'לחיצת רגליים במכונה' },
    description: {
      en: 'Machine press for legs and glutes. Plan load: 45 kg.',
      he: 'לחיצת רגליים במכונה לרגליים ולישבן. משקל בתוכנית: 45 ק״ג.',
    },
    instructions: {
      en: '1. Sit with the back against the pad.\n2. Place feet high on the platform, about shoulder-width.\n3. Press until the knees are almost straight, without locking.\n4. Return slowly.\nBreathe: exhale on the press, inhale on the return.',
      he: '1. שב במכונה, גב צמוד למושב.\n2. הנח כפות רגליים בחלק העליון של הפלטפורמה ברוחב הכתפיים.\n3. דחוף את הפלטפורמה עד יישור כמעט מלא של הברכיים, בלי לנעול.\n4. חזור לאט.\nנשימה: נושף בדחיפה, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-leg-press.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    repetitions: 10,
    targetMuscles: ['quadriceps', 'glutes'],
    equipment: 'machine',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-chest-press',
    name: { en: 'Chest Press / Pec Deck', he: 'לחיצת חזה / מכונת פרפר' },
    description: {
      en: 'Chest press with dumbbells or pec-deck machine. Plan: 18 kg machine or 4–5 kg dumbbells.',
      he: 'לחיצת חזה עם משקולות או מכונת פרפר. בתוכנית: 18 ק״ג במכונה או 4–5 ק״ג במשקולות.',
    },
    instructions: {
      en: '1. Lie on the bench with feet planted, or sit in the pec deck.\n2. Hold the weights or handles at chest height.\n3. Press or bring the arms together over the chest.\n4. Return slowly.\nBreathe: inhale on the opening, exhale on the press.',
      he: '1. בשכיבה על ספסל, רגליים יציבות על הרצפה — או ישיבה במכונת פרפר.\n2. הרם משקולות מעל החזה, או אחוז בידיות.\n3. הורד באיטיות לרוחב החזה ודחוף חזרה, או קרב ידיים מול החזה.\nנשימה: שואף בפתיחה, נושף בסגירה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-chest-press.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    repetitions: 10,
    targetMuscles: ['chest'],
    equipment: 'dumbbells',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-incline-chest-press',
    name: { en: 'Incline Chest Press', he: 'לחיצת חזה עליון במכונה' },
    description: {
      en: 'Machine press on a positive incline for the upper chest. Use a low seat.',
      he: 'לחיצת חזה במכונה בזווית חיובית לחזה העליון. כסא נמוך.',
    },
    instructions: {
      en: '1. Sit on a roughly 30° incline so the handles are at chest height.\n2. Hold the handles at the chest.\n3. Press forward until the arms are almost straight.\n4. Return slowly with the back on the pad.\nBreathe: exhale on the press, inhale on the return.',
      he: '1. שב במכונה בזווית חיובית (כ-30 מעלות).\n2. אחוז בידיות בגובה החזה.\n3. דחוף קדימה עד יישור זרועות.\n4. חזור לאט.\nנשימה: נושף בדחיפה, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-incline-chest-press.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    repetitions: 10,
    targetMuscles: ['chest', 'shoulders'],
    equipment: 'machine',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-lat-pulldown',
    name: { en: 'Wide-Grip Lat Pulldown', he: 'חתירה אחיזה רחבה בפולי' },
    description: {
      en: 'Cable pulldown with a wide grip for the lats. Plan load: 24 kg.',
      he: 'משיכה בפולי באחיזה רחבה לגב הרחב. משקל בתוכנית: 24 ק״ג.',
    },
    instructions: {
      en: '1. Hold the bar wider than the shoulders.\n2. Pull the bar down to the chest.\n3. Pause with the chest up.\n4. Return until the arms are straight.\nBreathe: exhale on the pull, inhale on the return.',
      he: '1. אחוז במוט רחב, כפות ידיים מעבר לכתפיים.\n2. משוך את המוט כלפי מטה לחזה.\n3. עצור עם חזה פתוח.\n4. חזור לאט ליישור זרועות.\nנשימה: נושף במשיכה, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-lat-pulldown.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    repetitions: 10,
    targetMuscles: ['back'],
    equipment: 'cable',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-seated-row',
    name: { en: 'Seated Row', he: 'חתירה אחיזה צרה במכונה' },
    description: {
      en: 'Close-grip seated row for mid-back and shoulder blades. Plan load: 45 kg.',
      he: 'חתירה בישיבה באחיזה צרה לגב אמצעי ולשכמות. משקל בתוכנית: 45 ק״ג.',
    },
    instructions: {
      en: '1. Sit tall and hold the close handles.\n2. Pull them toward the belly, elbows close.\n3. Squeeze the shoulder blades together.\n4. Return slowly.\nBreathe: exhale on the pull, inhale on the return.',
      he: '1. שב זקוף, אחוז בידיות קרובות.\n2. משוך אותן לכיוון הבטן בצמוד לגוף.\n3. כווץ את השכמות יחד.\n4. חזור לאט.\nנשימה: נושף במשיכה, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-seated-row.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    repetitions: 10,
    targetMuscles: ['back'],
    equipment: 'machine',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-bicep-curl',
    name: { en: 'Bicep Curl', he: 'כפיפת מרפק ליד קדמית' },
    description: {
      en: 'Seated dumbbell curl for the biceps. Plan load: 4–5 kg.',
      he: 'כפיפת מרפק בישיבה ליד הקדמית. משקל בתוכנית: 4–5 ק״ג.',
    },
    instructions: {
      en: '1. Sit tall, holding dumbbells with elbows close to the body.\n2. Curl the weights toward the shoulders.\n3. Lower slowly without swinging.\nBreathe: exhale on the curl, inhale on the way down.',
      he: '1. שב זקוף, כפות ידיים אוחזות במשקולות.\n2. כופף מרפקים והבא את המשקולות לכיוון הכתפיים.\n3. הורד לאט בלי לנענע.\nנשימה: נושף בעלייה, שואף בירידה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-bicep-curl.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'both',
    repetitions: 10,
    targetMuscles: ['shoulders'],
    equipment: 'dumbbells',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-triceps-pushdown',
    name: { en: 'Triceps Pushdown', he: 'פשיטת מרפק ליד אחורית בפולי' },
    description: {
      en: 'Cable pushdown for the triceps. Plan load: 24 kg.',
      he: 'לחיצה מטה בפולי ליד האחורית. משקל בתוכנית: 24 ק״ג.',
    },
    instructions: {
      en: '1. Stand tall and hold the handle or rope.\n2. Keep the elbows pinned to the sides.\n3. Push down until the elbows straighten, then squeeze.\n4. Return slowly.\nBreathe: exhale on the press, inhale on the return.',
      he: '1. עמוד זקוף, אחוז בידית או בחבל.\n2. משוך כלפי מטה עד יישור מרפקים.\n3. כווץ למטה.\n4. חזור לאט.\nנשימה: נושף בלחיצה, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-triceps-pushdown.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    repetitions: 10,
    targetMuscles: ['shoulders'],
    equipment: 'cable',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-front-lateral-raise',
    name: { en: 'Front and Lateral Raise', he: 'הרמת ידיים קדימה וצידית' },
    description: {
      en: 'Dumbbell raises to the front and to the side. Plan: 10+10 at 3 kg.',
      he: 'הרמת ידיים קדימה ואז הצידה. בתוכנית: 10+10 עם 3 ק״ג.',
    },
    instructions: {
      en: '1. Front raise: lift a straight arm forward to shoulder height.\n2. Lateral raise: lift the arm out to the side to shoulder height.\n3. Lower slowly. Do not swing.\nBreathe: exhale on the lift, inhale on the return.',
      he: '1. הרמה קדימה: הרם יד ישרה קדימה עד גובה הכתף.\n2. הרמה צידית: הרם יד הצידה עד גובה הכתף.\n3. הורד לאט.\nנשימה: נושף בהרמה, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-front-lateral-raise.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'both',
    repetitions: 10,
    targetMuscles: ['shoulders'],
    equipment: 'dumbbells',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-w-raise',
    name: { en: 'W Raise', he: 'כתף אחורית ושכמות — W' },
    description: {
      en: 'Band or cable pull into a W for rear shoulders and shoulder blades. Light band.',
      he: 'משיכה לאחור לצורת W לכתף אחורית ולשכמות. גומיה דקה.',
    },
    instructions: {
      en: '1. Hold a light band or cable handles.\n2. Pull back and open the elbows into a W.\n3. Squeeze the shoulder blades.\n4. Return slowly.\nBreathe: exhale on the pull, inhale on the return.',
      he: '1. אחוז בגומייה או בידיות בפולי.\n2. משוך לאחור ופתח את המרפקים לצורת W.\n3. כווץ שכמות.\n4. חזור לאט.\nנשימה: נושף במשיכה, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-w-raise.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'both',
    repetitions: 10,
    targetMuscles: ['shoulders', 'back'],
    equipment: 'resistanceBand',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-external-rotation',
    name: { en: 'External Rotation', he: 'סיבוב חיצוני לשכמות' },
    description: {
      en: 'Light-band external rotation for the rotator cuff. 8–10 slow reps.',
      he: 'סיבוב חיצוני עם גומיה דקה למסובבי הכתף. 8–10 חזרות איטיות.',
    },
    instructions: {
      en: '1. Hold a light band or cable.\n2. Bend the elbow to 90° and keep it against the side.\n3. Rotate the forearm outward.\n4. Return slowly.\nBreathe: exhale on the rotation, inhale on the return.',
      he: '1. אחוז בגומייה או בידית בפולי.\n2. כופף מרפק 90 מעלות והצמד לגוף.\n3. סובב את האמה החוצה.\n4. חזור לאט.\nנשימה: נושף בסיבוב, שואף בחזרה.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-external-rotation.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'both',
    repetitions: 10,
    targetMuscles: ['shoulders'],
    equipment: 'resistanceBand',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-bosu-hold',
    name: { en: 'Bosu Hold', he: 'תרגיל בטן על בוסו' },
    description: {
      en: 'A stable core hold on the bosu, 30–45 seconds.',
      he: 'אחיזת ליבה על בוסו, 30–45 שניות.',
    },
    instructions: {
      en: '1. Lie on the bosu with the low back supported.\n2. Keep the spine long and the belly active.\n3. Hold 30–45 seconds without rocking.',
      he: '1. שכיבה על בוסו בלבד, שמור על גב ישר ובטן פעילה.\n2. החזק 30–45 שניות בלי להתנדנד.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-bosu-hold.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'gym',
    duration: 45,
    targetMuscles: ['core'],
    equipment: 'mat',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-superman',
    name: { en: 'Superman', he: 'סופרמן' },
    description: {
      en: 'Lie on the stomach and lift arms and legs for the back extensors.',
      he: 'שכיבה על הבטן והרמת ידיים ורגליים לזוקפי הגב.',
    },
    instructions: {
      en: '1. Lie face down, arms reaching forward.\n2. Lift the arms and legs a comfortable amount.\n3. Pause, then lower.\n4. Do 10–12 controlled reps.',
      he: '1. שכב על הבטן, ידיים קדימה.\n2. הרם ידיים ורגליים בטווח נוח.\n3. עצור והורד.\n4. 10–12 חזרות.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-superman.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'both',
    repetitions: 12,
    targetMuscles: ['back', 'core'],
    equipment: 'mat',
    active: true,
    deleted: false,
  },
  {
    clientId: 'ex-dolphin',
    name: { en: 'Dolphin', he: 'דולפין' },
    description: {
      en: 'A short hold for back extensors and balance, 20–30 seconds.',
      he: 'אחיזה קצרה לזוקפי הגב ולשיווי משקל, 20–30 שניות.',
    },
    instructions: {
      en: '1. Set up in a stable face-down or forearm position as coached.\n2. Keep the body long and still.\n3. Hold 20–30 seconds.',
      he: '1. התמקם בתנוחה יציבה לפי ההדרכה.\n2. שמור על גוף ארוך ויציב.\n3. החזק 20–30 שניות.',
    },
    safetyNotes: safetyDefault,
    photo: 'assets/exercises/ex-dolphin.png',
    category: 'strength',
    difficulty: 'beginner',
    venue: 'both',
    duration: 30,
    targetMuscles: ['back', 'core'],
    equipment: 'mat',
    active: true,
    deleted: false,
  },
]
